
spring:
  application:
    name: todo-app
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:mysql-domeki.alwaysdata.net}:3306/domeki_banco
    username: domeki
    password: irascema
    driver-class-name: com.mysql.cj.jdbc.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL57Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher    